# Generated by Django 4.1.7 on 2023-05-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_planet_application', '0004_alter_hackathon_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submission',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
